### ISSUE TITLE
Only US data location tables show in explorer?

### ISSUE THREAD

**Issue by ggianfran** [evidence-dev/sqltools-bigquery-driver#4]
It seems that only tables which have datalocation US show up in the explorer. None of my EU tables appear

**Comment by archiewood** [comment]
Hmm, all my test data is in the US, so missed this.

It seems like bigquery default to showing data from the US if you don't specify

https://cloud.google.com/bigquery/docs/information-schema-datasets-schemata#scope_and_syntax

Should just be a case of updating the queries that get the information schemas to check other regions too.

**Comment by archiewood** [comment]
Need to sort out #5 first.

Currently if you search in regions that dont have tables you get an error - so this needs to be rectified

**Comment by archiewood** [comment]
This is now unblocked

**Comment by archiewood** [comment]
You can now specify the location of the dataset when you set up a connection.

Due to a BQ limitation, you cannot see all tables from all regions in one connection. To see tables from multiple regions you need to add multiple connections

<img width="389" alt="image" src="https://github.com/evidence-dev/sqltools-bigquery-driver/assets/58074498/d9c219c7-e4ce-40b3-92e3-795ea96438ab">
